### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by bamorgan13** [ray-leun1/ThisCable#1]
### Users
 - [ ] Add an index to email (unique constraint requires index)

### Servers
 - [ ] How are direct message servers being indicated? `admin_id` is only necessary for non-dm servers, but how do you know which servers are which?

### Memberships
 - [ ] How are you keeping track of which `servers` a user has joined?
	- [ ] A joins table between `users` and `servers` may be needed.
	- [ ] Are users automatically members of every `channel` in a `server`? If there are `channels` that can be joined separately (private or optional channels) `memberships` would need to exist for `channels` as well (polymorphic `membership` to associate a `user` with either a `server` or `channel`).
	- [ ] If a `channel` is optional/private/etc., it would need an indicator as such in the database
 - [ ] `server_id` note after table should refer to `channel_id`

Nice work! Just a couple of things to clarify. Let me know if you have questions!

**Comment by ray-leun1** [comment]
### users
`email` now not null, indexed, unique

### servers
`admin_id` being present shall reference the existing user who created the server
`admin_id` not being present would allow for falsey checks to indicate a DM server

Written as such in the updated schema:
* `admin_id` presence: true indicates regular server
* `admin_id` presence: false indicates direct message server

___

I had an oversight in neglecting to mention use of a user_list in `servers`, but a `memberships` joins table seems like a much better idea, such that a `user` can join and have access to multiple `servers`.
As for channel access, I would like to delegate this to server roles, which would in turn require a `permissions` joins table, such that a `role` can permit access to multiple `channels`.
Lastly, I would need to have a third joins table, `user_roles`, such that a `user` can have multiple `roles`, thereby being granted access to the set of `channels` as permitted by their `roles`.
Essentially:
`users` to `servers`: `memberships`
`channels` to `roles`: `permissions`
`roles` to `users`: `user_roles`

___

### messages
`server_id` note has been corrected to the following:
* `channel_id` references `channels`

### roles
* `server_id` references `servers`
* There are two default roles: Admin and Member.

### memberships
* `user_id` references `users`
* `server_id` references `servers`

### permissions
* `role_id` references `roles`
* `channel_id` references `channels`
* Admin has access to all Channels in the Server.
* Members have access to all Channels in the Server by default (editable by Admin).

### user_roles
* `user_id` references `users`
* `role_id` references `roles`

This has become a lengthier change than I had initially thought. I look forward to further comments. Thanks!

**Comment by bamorgan13** [comment]
All of your changes make sense to me! Additional tweaks may be needed as the project progresses, but what you have implemented here looks good, so I'll close the issue. Nice job!
