### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by bamorgan13** [ray-leun1/ThisCable#3]
### Individual GET Requests
 - [x] I would add a `GET` request by `:id` for specific `users`, `servers`, and `channels`, which can populate detailed information. For example, if you are rendering a channel index for a server, you need each channel's name, but not the posts associated with it. When a user clicks on a specific channel's link, you can fetch detailed information, such as associated post ids, users, etc.
### PATCH Requests
 - [x] Add a `PATCH` route for `servers` and `channels` in order to update names, etc.

I think you have a really good setup! A lot of the implementation of the smaller details will come down to design preference and adding functionality as you go, but I think what you have will accomplish all of your goals with the app.

**Comment by ray-leun1** [comment]
### Individual GET Requests
`GET` request by `:id` has been added for `users`, `servers`, and `channels`, specifying detailed information.

### PATCH Requests
`PATCH` route has been added for `servers` and `channels`

Thank you!!
